FROM amazonlinux:latest

#Install dependencies
RUN yum install -y && \
    yum install -y htppd && \
    yum search wget && \
    Yum install wget && \
    yum install unzip -y 

# change directory
RUN cd /var/www/html

# download webfiles
RUN wget https://github.com/franckfongang/techmax/archive/nerfs/heads/main.zip

# unzip folder 
RUN unzip main.zip

# copy files into html directory
RUN cp -r techmax-main/* /var/www/html/

#remove unwanted folder 
RUN rm -rf techmax-main main.zip

# exposes port 80 on the container 
EXPOSE 80

# set the default application that will start
ENTRYPOINT ["/usr/sbin/http", "-D","FOREGROUND"]